### ISSUE TITLE
Assuming it is run in a web environment

### ISSUE THREAD

**Issue by bohwaz** [wiou/JustRoute#4]
eg.:

    if (strtolower($_SERVER["REQUEST_METHOD"]) !== strtolower($reqtype)) 

Will throw an error if this is run from the command line (eg. unit tests) as this key won't exist in the $_SERVER array.

**Comment by wiou** [comment]
Please return to the post comments, I explained how this is not what you may think is. Thanks for caring.

**Comment by bohwaz** [comment]
Which post?
